// ===========================================
// File Location :
// src/Application/Platform.Pipeline/Models/ExecutionLogEntry.cs
// ===========================================
namespace Platform.Pipeline.Models;

/// <summary>
/// Represents execution log information.
///
/// Responsibility:
/// - Capture request execution metadata.
/// - Capture execution outcome.
/// - Capture execution duration.
/// - Capture execution timestamp.
///
/// Usage:
/// - Created by LoggingBehavior.
/// - Created by LoggingBehaviorT.
/// - Persisted through IExecutionLogger.
///
/// Side Effects:
/// - None.
///
/// Thread Safety:
/// - Immutable record.
/// </summary>
/// <param name="RequestName">
/// Gets request type name.
///
/// Examples:
/// - CreateUserCommand
/// - AssignRoleCommand
/// - EnableMfaCommand
/// </param>
/// <param name="Success">
/// Gets operation success indicator.
///
/// True:
/// - Request completed successfully.
///
/// False:
/// - Request failed.
/// </param>
/// <param name="ErrorCode">
/// Gets error code when request fails.
///
/// Examples:
/// - VALIDATION.FAILED
/// - IDENTITY.USER_NOT_FOUND
/// - IDENTITY.ROLE_ALREADY_ASSIGNED
///
/// Null:
/// - Request succeeded.
/// </param>
/// <param name="DurationMs">
/// Gets execution duration in milliseconds.
///
/// Business Rule:
/// - Must be greater than or equal to zero.
/// </param>
/// <param name="TimestampUtc">
/// Gets UTC timestamp when the execution
/// completed.
///
/// Business Rule:
/// - Must use UTC time.
/// - Must be generated by pipeline behavior.
/// </param>
public sealed record ExecutionLogEntry(
    string RequestName,
    bool Success,
    string? ErrorCode,
    string? ExceptionType,
    long DurationMs,
    DateTime TimestampUtc);