// ===========================================
// File Location :
// tests/Platform.Persistence.UnitTests/
// Configurations/RoleConfigurationTests.cs
// ===========================================

using Microsoft.EntityFrameworkCore.Metadata;
using Platform.Identity.Domain.Aggregates;
using Platform.Identity.Domain.ValueObjects;
using Platform.Persistence.Configurations;

namespace Platform.Persistence.UnitTests.Configurations;

/// <summary>
/// Contains unit tests for the
/// <see cref="RoleConfiguration"/> class.
///
/// Responsibility:
/// - Verify role table mapping.
/// - Verify role primary key configuration.
/// - Verify role scalar property configuration.
/// - Verify role name unique index configuration.
/// - Verify role scope value conversion.
/// - Verify permission owned collection mapping.
/// - Verify permission foreign key configuration.
/// - Verify permission composite key configuration.
/// - Verify permission backing field configuration.
/// - Verify ignored domain event mapping.
/// - Verify null builder validation.
///
/// Testing Strategy:
/// - Exercise the public Configure method.
/// - Inspect the resulting EF Core model metadata.
/// - Do not access private configuration methods directly.
/// - Do not require a physical database.
/// </summary>
public sealed class RoleConfigurationTests
{
    /// <summary>
    /// Creates an EF Core model containing the
    /// <see cref="RoleConfiguration"/> mapping.
    ///
    /// The model is created entirely in memory so that
    /// persistence metadata can be verified without
    /// connecting to a database.
    /// </summary>
    /// <returns>
    /// The configured mutable EF Core model.
    /// </returns>
    private static IMutableModel CreateModel()
    {
        var modelBuilder = new ModelBuilder();

        modelBuilder.ApplyConfiguration(
            new RoleConfiguration());

        return modelBuilder.Model;
    }

    /// <summary>
    /// Verifies that Configure throws an
    /// <see cref="ArgumentNullException"/> when
    /// the entity builder is null.
    /// </summary>
    [Fact]
    public void Configure_Should_ThrowArgumentNullException_When_BuilderIsNull()
    {
        // Arrange
        var sut = new RoleConfiguration();

        // Act
        Action act = () => sut.Configure(null!);

        // Assert
        act.Should()
            .Throw<ArgumentNullException>();
    }

    /// <summary>
    /// Verifies that Role is mapped to the
    /// IdentityRoles table.
    /// </summary>
    [Fact]
    public void Configure_Should_MapRoleToIdentityRolesTable()
    {
        // Arrange
        var model = CreateModel();

        // Act
        var entityType = model.FindEntityType(
            typeof(Role));

        // Assert
        entityType.Should()
            .NotBeNull();

        entityType!
            .GetTableName()
            .Should()
            .Be("IdentityRoles");
    }

    /// <summary>
    /// Verifies that Role.Id is configured as the
    /// primary key and that its value is never
    /// generated by the database.
    /// </summary>
    [Fact]
    public void Configure_Should_ConfigureIdAsNonGeneratedPrimaryKey()
    {
        // Arrange
        var model = CreateModel();

        var entityType = model.FindEntityType(
            typeof(Role));

        entityType.Should()
            .NotBeNull();

        // Act
        var primaryKey = entityType!
            .FindPrimaryKey();

        var idProperty = entityType.FindProperty(
            nameof(Role.Id));

        // Assert
        primaryKey.Should()
            .NotBeNull();

        primaryKey!
            .Properties
            .Should()
            .ContainSingle();

        primaryKey.Properties[0]
            .Name
            .Should()
            .Be(nameof(Role.Id));

        idProperty.Should()
            .NotBeNull();

        idProperty!
            .ValueGenerated
            .Should()
            .Be(ValueGenerated.Never);
    }

    /// <summary>
    /// Verifies that Role.Name is required
    /// and has a maximum length of 200 characters.
    /// </summary>
    [Fact]
    public void Configure_Should_ConfigureNameAsRequiredWithMaximumLength()
    {
        // Arrange
        var model = CreateModel();

        var entityType = model.FindEntityType(
            typeof(Role));

        entityType.Should()
            .NotBeNull();

        // Act
        var property = entityType!
            .FindProperty(nameof(Role.Name));

        // Assert
        property.Should()
            .NotBeNull();

        property!
            .IsNullable
            .Should()
            .BeFalse();

        property
            .GetMaxLength()
            .Should()
            .Be(200);
    }

    /// <summary>
    /// Verifies that Role.Name has a unique
    /// database index.
    /// </summary>
    [Fact]
    public void Configure_Should_CreateUniqueIndexForName()
    {
        // Arrange
        var model = CreateModel();

        var entityType = model.FindEntityType(
            typeof(Role));

        entityType.Should()
            .NotBeNull();

        // Act
        var indexes = entityType!
            .GetIndexes()
            .Where(index =>
                index.Properties.Count == 1
                && index.Properties[0].Name
                    == nameof(Role.Name))
            .ToList();

        // Assert
        indexes.Should()
            .ContainSingle();

        indexes[0]
            .IsUnique
            .Should()
            .BeTrue();
    }

    /// <summary>
    /// Verifies that IsSystemRole, IsActive,
    /// and CreatedAt are configured as required
    /// persistence properties.
    /// </summary>
    [Fact]
    public void Configure_Should_ConfigureRequiredScalarProperties()
    {
        // Arrange
        var model = CreateModel();

        var entityType = model.FindEntityType(
            typeof(Role));

        entityType.Should()
            .NotBeNull();

        // Act
        var isSystemRole = entityType!
            .FindProperty(nameof(Role.IsSystemRole));

        var isActive = entityType
            .FindProperty(nameof(Role.IsActive));

        var createdAt = entityType
            .FindProperty(nameof(Role.CreatedAt));

        // Assert
        isSystemRole.Should()
            .NotBeNull();

        isSystemRole!
            .IsNullable
            .Should()
            .BeFalse();

        isActive.Should()
            .NotBeNull();

        isActive!
            .IsNullable
            .Should()
            .BeFalse();

        createdAt.Should()
            .NotBeNull();

        createdAt!
            .IsNullable
            .Should()
            .BeFalse();
    }

    /// <summary>
    /// Verifies that Role.Scope uses a value converter,
    /// is persisted as a string, uses the Scope column,
    /// has a maximum length of 100 characters,
    /// and is required.
    /// </summary>
    [Fact]
    public void Configure_Should_ConfigureRoleScopeConversion()
    {
        // Arrange
        var model = CreateModel();

        var entityType = model.FindEntityType(
            typeof(Role));

        entityType.Should()
            .NotBeNull();

        // Act
        var property = entityType!
            .FindProperty(nameof(Role.Scope));

        // Assert
        property.Should()
            .NotBeNull();

        var converter = property!
            .GetValueConverter();

        converter.Should()
            .NotBeNull();

        converter!
            .ModelClrType
            .Should()
            .Be(typeof(RoleScope));

        converter
            .ProviderClrType
            .Should()
            .Be(typeof(string));

        property
            .GetColumnName()
            .Should()
            .Be("Scope");

        property
            .GetMaxLength()
            .Should()
            .Be(100);

        property
            .IsNullable
            .Should()
            .BeFalse();
    }

    /// <summary>
    /// Verifies that the configured RoleScope converter
    /// converts a RoleScope domain value object into
    /// its string persistence representation.
    /// </summary>
    [Fact]
    public void Configure_Should_ConvertRoleScopeToString()
    {
        // Arrange
        var model = CreateModel();

        var entityType = model.FindEntityType(
            typeof(Role));

        entityType.Should()
            .NotBeNull();

        var property = entityType!
            .FindProperty(nameof(Role.Scope));

        property.Should()
            .NotBeNull();

        var converter = property!
            .GetValueConverter();

        converter.Should()
            .NotBeNull();

        var scope = RoleScope.Global;

        // Act
        var converted =
            converter!
                .ConvertToProviderExpression
                .Compile()
                .DynamicInvoke(scope);

        // Assert
        converted.Should()
            .Be("GLOBAL");
    }

    /// <summary>
    /// Verifies that the configured RoleScope converter
    /// converts a persisted string into a RoleScope
    /// domain value object.
    /// </summary>
    [Fact]
    public void Configure_Should_ConvertStringToRoleScope()
    {
        // Arrange
        var model = CreateModel();

        var entityType = model.FindEntityType(
            typeof(Role));

        entityType.Should()
            .NotBeNull();

        var property = entityType!
            .FindProperty(nameof(Role.Scope));

        property.Should()
            .NotBeNull();

        var converter = property!
            .GetValueConverter();

        converter.Should()
            .NotBeNull();

        // Act
        var converted =
            converter!
                .ConvertFromProviderExpression
                .Compile()
                .DynamicInvoke("GLOBAL");

        // Assert
        converted.Should()
            .BeOfType<RoleScope>();

        ((RoleScope)converted!)
            .Value
            .Should()
            .Be("GLOBAL");
    }

    /// <summary>
    /// Verifies that PermissionIds is configured
    /// as an owned collection and that its owned
    /// entity is mapped to IdentityRolePermissions.
    /// </summary>
    [Fact]
    public void Configure_Should_ConfigurePermissionOwnedCollection()
    {
        // Arrange
        var model = CreateModel();

        var roleEntityType = model.FindEntityType(
            typeof(Role));

        roleEntityType.Should()
            .NotBeNull();

        // Act
        var navigation = roleEntityType!
            .FindNavigation(
                nameof(Role.PermissionIds));

        // Assert
        navigation.Should()
            .NotBeNull();

        navigation!
            .TargetEntityType
            .GetTableName()
            .Should()
            .Be("IdentityRolePermissions");
    }

    /// <summary>
    /// Verifies that the permission owned entity
    /// contains a RoleId property and uses it as
    /// the foreign key to Role.
    /// </summary>
    [Fact]
    public void Configure_Should_ConfigurePermissionForeignKey()
    {
        // Arrange
        var model = CreateModel();

        var roleEntityType = model.FindEntityType(
            typeof(Role));

        roleEntityType.Should()
            .NotBeNull();

        var navigation = roleEntityType!
            .FindNavigation(
                nameof(Role.PermissionIds));

        navigation.Should()
            .NotBeNull();

        var ownedEntityType = navigation!
            .TargetEntityType;

        // Act
        var roleIdProperty = ownedEntityType
            .FindProperty("RoleId");

        var foreignKeys = ownedEntityType
            .GetForeignKeys()
            .Where(foreignKey =>
                foreignKey.Properties
                    .Any(property =>
                        property.Name == "RoleId"))
            .ToList();

        // Assert
        roleIdProperty.Should()
            .NotBeNull();

        foreignKeys.Should()
            .ContainSingle();

        foreignKeys[0]
            .PrincipalEntityType
            .ClrType
            .Should()
            .Be(typeof(Role));
    }

    /// <summary>
    /// Verifies that the permission value property
    /// is persisted as PermissionCode with a maximum
    /// length of 200 characters and is required.
    /// </summary>
    [Fact]
    public void Configure_Should_ConfigurePermissionCodeColumn()
    {
        // Arrange
        var model = CreateModel();

        var roleEntityType = model.FindEntityType(
            typeof(Role));

        roleEntityType.Should()
            .NotBeNull();

        var navigation = roleEntityType!
            .FindNavigation(
                nameof(Role.PermissionIds));

        navigation.Should()
            .NotBeNull();

        var ownedEntityType = navigation!
            .TargetEntityType;

        // Act
        var permissionValue = ownedEntityType
            .FindProperty("Value");

        // Assert
        permissionValue.Should()
            .NotBeNull();

        permissionValue!
            .GetColumnName()
            .Should()
            .Be("PermissionCode");

        permissionValue
            .GetMaxLength()
            .Should()
            .Be(200);

        permissionValue
            .IsNullable
            .Should()
            .BeFalse();
    }

    /// <summary>
    /// Verifies that the permission owned entity
    /// uses RoleId and PermissionCode as its
    /// composite primary key.
    /// </summary>
    [Fact]
    public void Configure_Should_ConfigurePermissionCompositeKey()
    {
        // Arrange
        var model = CreateModel();

        var roleEntityType = model.FindEntityType(
            typeof(Role));

        roleEntityType.Should()
            .NotBeNull();

        var navigation = roleEntityType!
            .FindNavigation(
                nameof(Role.PermissionIds));

        navigation.Should()
            .NotBeNull();

        var ownedEntityType = navigation!
            .TargetEntityType;

        // Act
        var primaryKey = ownedEntityType
            .FindPrimaryKey();

        // Assert
        primaryKey.Should()
            .NotBeNull();

        primaryKey!
            .Properties
            .Select(property => property.Name)
            .Should()
            .Equal(
                "RoleId",
                "Value");
    }

    /// <summary>
    /// Verifies that the PermissionIds navigation
    /// uses the _permissionIds backing field and
    /// field property access.
    /// </summary>
    [Fact]
    public void Configure_Should_ConfigurePermissionNavigationUsingBackingField()
    {
        // Arrange
        var model = CreateModel();

        var entityType = model.FindEntityType(
            typeof(Role));

        entityType.Should()
            .NotBeNull();

        // Act
        var navigation = entityType!
            .FindNavigation(
                nameof(Role.PermissionIds));

        // Assert
        navigation.Should()
            .NotBeNull();

        navigation!
            .FieldInfo
            .Should()
            .NotBeNull();

        navigation
            .FieldInfo!
            .Name
            .Should()
            .Be("_permissionIds");

        navigation
            .GetPropertyAccessMode()
            .Should()
            .Be(PropertyAccessMode.Field);
    }

    /// <summary>
    /// Verifies that DomainEvents is excluded
    /// from Entity Framework Core persistence mapping.
    /// </summary>
    [Fact]
    public void Configure_Should_IgnoreDomainEvents()
    {
        // Arrange
        var model = CreateModel();

        var entityType = model.FindEntityType(
            typeof(Role));

        entityType.Should()
            .NotBeNull();

        // Act
        var property = entityType!
            .FindProperty(
                nameof(Role.DomainEvents));

        var navigation = entityType
            .FindNavigation(
                nameof(Role.DomainEvents));

        // Assert
        property.Should()
            .BeNull();

        navigation.Should()
            .BeNull();
    }

    /// <summary>
    /// Verifies that Configure produces the expected
    /// complete persistence metadata for the Role aggregate.
    /// </summary>
    [Fact]
    public void Configure_Should_ConfigureCompleteRolePersistenceModel()
    {
        // Arrange
        var model = CreateModel();

        // Act
        var roleEntityType = model.FindEntityType(
            typeof(Role));

        roleEntityType.Should()
            .NotBeNull();

        var permissionNavigation =
            roleEntityType!
                .FindNavigation(
                    nameof(Role.PermissionIds));

        // Assert
        roleEntityType
            .GetTableName()
            .Should()
            .Be("IdentityRoles");

        roleEntityType
            .FindPrimaryKey()!
            .Properties
            .Select(property => property.Name)
            .Should()
            .Equal(nameof(Role.Id));

        roleEntityType
            .FindProperty(nameof(Role.Name))!
            .GetMaxLength()
            .Should()
            .Be(200);

        roleEntityType
            .FindProperty(nameof(Role.Name))!
            .IsNullable
            .Should()
            .BeFalse();

        roleEntityType
            .FindProperty(nameof(Role.Scope))!
            .GetMaxLength()
            .Should()
            .Be(100);

        roleEntityType
            .FindProperty(nameof(Role.Scope))!
            .GetValueConverter()
            .Should()
            .NotBeNull();

        permissionNavigation.Should()
            .NotBeNull();

        permissionNavigation!
            .TargetEntityType
            .GetTableName()
            .Should()
            .Be("IdentityRolePermissions");

        permissionNavigation
            .TargetEntityType
            .FindPrimaryKey()!
            .Properties
            .Select(property => property.Name)
            .Should()
            .Equal(
                "RoleId",
                "Value");

        roleEntityType
            .FindProperty(
                nameof(Role.DomainEvents))
            .Should()
            .BeNull();
    }
}