// ===========================================
// File Location :
// src/Application/Platform.Identity.Application/
// Contracts/Authentications/Dtos/
// LoginContextDto.cs
// ===========================================

namespace Platform.Identity.Application.Contracts.Authentication.Dtos;

/// <summary>
/// Represents contextual information associated with a login request.
///
/// <para>
/// This data transfer object carries security-related metadata collected
/// from the client environment and infrastructure during an authentication
/// request.
/// </para>
///
/// <para>
/// The information contained in this contract is independent from the
/// authentication credentials and is used to support:
/// </para>
///
/// <list type="bullet">
/// <item>
/// <description>
/// Zero Trust security evaluation.
/// </description>
/// </item>
/// <item>
/// <description>
/// Risk-based authentication.
/// </description>
/// </item>
/// <item>
/// <description>
/// Impossible travel detection.
/// </description>
/// </item>
/// <item>
/// <description>
/// Device recognition.
/// </description>
/// </item>
/// <item>
/// <description>
/// Security audit.
/// </description>
/// </item>
/// <item>
/// <description>
/// Governance and compliance logging.
/// </description>
/// </item>
/// </list>
///
/// <para>
/// This contract is immutable and contains no business logic,
/// validation logic, or infrastructure dependencies.
/// </para>
/// </summary>
/// <param name="IpAddress">
/// The client IP address from which the authentication request originated.
/// </param>
/// <param name="UserAgent">
/// The client user-agent string.
/// </param>
/// <param name="DeviceFingerprint">
/// A stable identifier representing the client device.
///
/// <para>
/// The value is generated by the presentation or infrastructure layer
/// and is used for device recognition during authentication.
/// </para>
/// </param>
/// <param name="CountryCode">
/// The ISO country code determined from the client location,
/// when available.
/// </param>
/// <param name="City">
/// The detected city associated with the client location,
/// when available.
/// </param>
/// <param name="Latitude">
/// The client's latitude in decimal degrees,
/// when available.
/// </param>
/// <param name="Longitude">
/// The client's longitude in decimal degrees,
/// when available.
/// </param>
public sealed record LoginContextDto(
    string IpAddress,
    string UserAgent,
    string DeviceFingerprint,
    string? CountryCode,
    string? City,
    double? Latitude,
    double? Longitude);